name: policies-database
channels:
  - conda-forge
dependencies:
  - ipykernel=4.8.2
  - lxml=4.2.1
  - nbconvert=5.3.1
  - networkx=2.1
  - notebook=5.4.1
  - pandas=0.22.0
  - pykwalify=1.6.1
  - python=3.6.5
  - ruamel.yaml=0.15.37
